/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as PricingCheckoutIdRouteImport } from './routes/pricing.checkout.$id'
import { Route as AdminBuilderIdRouteImport } from './routes/admin.builder.$id'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminRoute,
} as any)
const PricingCheckoutIdRoute = PricingCheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => PricingRoute,
} as any)
const AdminBuilderIdRoute = AdminBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/admin/builder': typeof AdminBuilderRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/builder/$id': typeof AdminBuilderIdRoute
  '/pricing/checkout/$id': typeof PricingCheckoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/admin/builder': typeof AdminBuilderRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/builder/$id': typeof AdminBuilderIdRoute
  '/pricing/checkout/$id': typeof PricingCheckoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRoute
  '/admin/builder': typeof AdminBuilderRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/builder/$id': typeof AdminBuilderIdRoute
  '/pricing/checkout/$id': typeof PricingCheckoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/work'
    | '/admin/builder'
    | '/p/$slug'
    | '/admin/builder/$id'
    | '/pricing/checkout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/work'
    | '/admin/builder'
    | '/p/$slug'
    | '/admin/builder/$id'
    | '/pricing/checkout/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/contact'
    | '/journal'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/work'
    | '/admin/builder'
    | '/p/$slug'
    | '/admin/builder/$id'
    | '/pricing/checkout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pricing/checkout/$id': {
      id: '/pricing/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/pricing/checkout/$id'
      preLoaderRoute: typeof PricingCheckoutIdRouteImport
      parentRoute: typeof PricingRoute
    }
    '/admin/builder/$id': {
      id: '/admin/builder/$id'
      path: '/$id'
      fullPath: '/admin/builder/$id'
      preLoaderRoute: typeof AdminBuilderIdRouteImport
      parentRoute: typeof AdminBuilderRoute
    }
  }
}

interface AdminBuilderRouteChildren {
  AdminBuilderIdRoute: typeof AdminBuilderIdRoute
}

const AdminBuilderRouteChildren: AdminBuilderRouteChildren = {
  AdminBuilderIdRoute: AdminBuilderIdRoute,
}

const AdminBuilderRouteWithChildren = AdminBuilderRoute._addFileChildren(
  AdminBuilderRouteChildren,
)

interface AdminRouteChildren {
  AdminBuilderRoute: typeof AdminBuilderRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuilderRoute: AdminBuilderRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PricingRouteChildren {
  PricingCheckoutIdRoute: typeof PricingCheckoutIdRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingCheckoutIdRoute: PricingCheckoutIdRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
